name: Compile Paper

on:
  push:
    branches:
      - main
      - your-branch-name # Update with your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Pandoc
      run: sudo apt-get install pandoc

    - name: Compile paper
      run: pandoc JOSS_paper/paper.md -o JOSS_paper/paper.pdf --citeproc --bibliography=JOSS_paper/paper.bib

      working-directory: JOSS_paper

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: paper.pdf
        path: JOSS_paper/paper.pdf
