name: Compile Paper

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: pandoc/latex:latest

    steps:
    - uses: actions/checkout@v2

    - name: Compile paper
      run: |
        pandoc JOSS_paper/paper.md -o JOSS_paper/paper.pdf --citeproc --bibliography=JOSS_paper/paper.bib
