name: Compile Paper

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensures the entire repo history is checked out

    - name: Install Pandoc
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.14/pandoc-2.14-1-amd64.deb -O pandoc.deb
        sudo dpkg -i pandoc.deb
        pandoc --version

    - name: Compile paper
      run: pandoc JOSS_paper/paper.md -o JOSS_paper/paper.pdf --citeproc --bibliography=JOSS_paper/paper.bib
