name: Compile Paper

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Pandoc
      run: sudo apt-get install pandoc

    - name: Compile paper
      run: pandoc paper.md -o paper.pdf --filter pandoc-citeproc --bibliography=paper.bib

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: paper.pdf
        path: paper.pdf
